# Any starting with the prefix "my-", means that we can choose the name.

terraform {
  # terraform itself and configs
}

provider "aws" {
  # which provider we will use
}

resource "aws_instance" "my_vm_block" {
  # object to create in our provider
}

data "aws_ami" "my_ami_block" {
  # retrieve information from provider to use in our Terraform
}

module "my_custom_module" {
  # call a module local and/or remote
}

variable "my_name_variable" {
  # to create variables within Terraform
}

output "my_output" {
  # to output any information generated by our Terraform, for example dynamic IP instance
}

locals {
  # use for create functions or part code, to avoid repetition
}
